# Generated by Django 5.2.2 on 2025-06-06 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises', '0005_alter_analiseoleodegomado_horario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analiseoleodegomado',
            name='horario',
            field=models.TimeField(default=datetime.time(14, 52, 5, 514530), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseproteina',
            name='horario',
            field=models.TimeField(default=datetime.time(14, 52, 5, 514344), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseumidade',
            name='horario',
            field=models.TimeField(default=datetime.time(14, 52, 5, 513902), verbose_name='Horário da Análise'),
        ),
    ]
