# Generated by Django 5.2.2 on 2025-06-12 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises', '0014_analiseumidadeoleodegomado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analiseumidadeoleodegomado',
            name='titulacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Titulação'),
        ),
        migrations.AlterField(
            model_name='analiseproteina',
            name='horario',
            field=models.TimeField(default=datetime.time(8, 57, 5, 894366), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseumidade',
            name='horario',
            field=models.TimeField(default=datetime.time(8, 57, 5, 893002), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseumidadeoleodegomado',
            name='horario',
            field=models.TimeField(default=datetime.time(8, 57, 5, 894576), verbose_name='Horário da Análise'),
        ),
    ]
