# Generated by Django 5.2.2 on 2025-06-06 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoOleo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('hora', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OleoDegomado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tara', models.FloatField()),
                ('liquido', models.FloatField()),
                ('peso_amostra', models.FloatField()),
                ('resultado', models.FloatField()),
                ('umidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='umidade_tipoOleo', to='analise_oleo_degomado.tipooleo')),
            ],
        ),
    ]
