# Generated by Django 5.2.2 on 2025-06-07 19:28

import analise_oleo_degomado.models
import datetime
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise_oleo_degomado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseOleoDegomado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Última Atualização')),
                ('data', models.DateField(default=django.utils.timezone.localdate, validators=[analise_oleo_degomado.models.validate_not_future_date], verbose_name='Data da Análise')),
                ('horario', models.TimeField(default=datetime.time(15, 28, 38, 373044), verbose_name='Horário da Análise')),
                ('tipo_amostra', models.CharField(choices=[('OP', 'Óleo Produção'), ('OE', 'Óleo Expedição')], default='OP', max_length=2, verbose_name='Tipo de Amostra')),
                ('tara', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tara')),
                ('liquido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Líquido')),
                ('peso_amostra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso da Amostra')),
                ('resultado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Resultado')),
                ('fator_correcao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-1000), django.core.validators.MaxValueValidator(1000)], verbose_name='Fator de Correção')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
