# Generated by Django 5.2.2 on 2025-06-07 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise_oleo_degomado', '0002_analiseoleodegomado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analiseoleodegomado',
            name='horario',
            field=models.TimeField(default=datetime.time(15, 32, 44, 213131), verbose_name='Horário da Análise'),
        ),
        migrations.DeleteModel(
            name='OleoDegomado',
        ),
        migrations.DeleteModel(
            name='TipoOleo',
        ),
    ]
